#MariaDB_StartSpringBoot

#.properties
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/start_spring_boot
#spring.datasource.username=BlogOwner
#spring.datasource.password=rladlrgus!23
#server.servlet.context-path=/

#.yaml
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/start_spring_boot
    username: BlogOwner
    password: rladlrgus!23
  jpa:
    hibernate:
      ddl-auto: update #change later update or none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    #prefix: file:src/main/resources/templates
  devtools:
    restart:
      enabled: true

server:
  servlet:
    context-path: /

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace #show parameter binding